# GoReleaser configuration for StackEye CLI
# Documentation: https://goreleaser.com/customization/
version: 2

project_name: stackeye

# Git configuration
# Allow "dirty" state because CI modifies go.mod to point to checked-out SDK
# The .sdk/ directory is in .gitignore so it shows as untracked
git:
  ignore_tags:
    - nightly

# Generate documentation before build
before:
  hooks:
    - go run ./docs/man/generate.go
    - go run ./docs/markdown/generate.go

# Build configuration
builds:
  - id: stackeye
    binary: stackeye
    main: ./cmd/stackeye
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/StackEye-IO/stackeye-cli/internal/version.Version={{.Version}}
      - -X github.com/StackEye-IO/stackeye-cli/internal/version.Commit={{.ShortCommit}}
      - -X github.com/StackEye-IO/stackeye-cli/internal/version.Date={{.Date}}
      - -X github.com/StackEye-IO/stackeye-cli/internal/version.BuiltBy=goreleaser
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows ARM64 not commonly needed
      - goos: windows
        goarch: arm64

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/man/pages/*.1

# Linux package configuration (deb)
nfpms:
  - id: stackeye-deb
    package_name: stackeye
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: StackEye IO
    homepage: https://stackeye.io
    maintainer: StackEye IO <support@stackeye.io>
    description: "CLI for StackEye uptime monitoring platform"
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: utils
    priority: optional
    dependencies:
      - ca-certificates
    contents:
      - src: LICENSE
        dst: /usr/share/doc/stackeye/LICENSE
      - src: README.md
        dst: /usr/share/doc/stackeye/README.md
      - src: docs/man/pages/*.1
        dst: /usr/share/man/man1/

  # Linux package configuration (rpm)
  - id: stackeye-rpm
    package_name: stackeye
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: StackEye IO
    homepage: https://stackeye.io
    maintainer: StackEye IO <support@stackeye.io>
    description: "CLI for StackEye uptime monitoring platform"
    license: MIT
    formats:
      - rpm
    bindir: /usr/bin
    dependencies:
      - ca-certificates
    rpm:
      group: Applications/Internet
    contents:
      - src: LICENSE
        dst: /usr/share/doc/stackeye/LICENSE
      - src: README.md
        dst: /usr/share/doc/stackeye/README.md
      - src: docs/man/pages/*.1
        dst: /usr/share/man/man1/

# Docker image configuration
dockers:
  - id: stackeye-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=stackeye"
      - "--label=org.opencontainers.image.description=CLI for StackEye uptime monitoring platform"
      - "--label=org.opencontainers.image.url=https://stackeye.io"
      - "--label=org.opencontainers.image.source=https://github.com/StackEye-IO/stackeye-cli"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - id: stackeye-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=stackeye"
      - "--label=org.opencontainers.image.description=CLI for StackEye uptime monitoring platform"
      - "--label=org.opencontainers.image.url=https://stackeye.io"
      - "--label=org.opencontainers.image.source=https://github.com/StackEye-IO/stackeye-cli"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

# Multi-arch Docker manifest
docker_manifests:
  - name_template: "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}"
    image_templates:
      - "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}-amd64"
      - "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/stackeye-io/stackeye-cli:latest"
    image_templates:
      - "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}-amd64"
      - "ghcr.io/stackeye-io/stackeye-cli:{{ .Tag }}-arm64"

# Checksum configuration
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# GPG signing configuration
signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

# Wasabi S3 upload handled by AWS CLI in workflow (more reliable credential handling)
# CloudFlare CDN fronts releases.stackeye.io

# Snapshot configuration (for testing without tags)
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other
      order: 999

# Release configuration
release:
  github:
    owner: StackEye-IO
    name: stackeye-cli
  draft: false
  prerelease: auto
  mode: replace
  name_template: "StackEye CLI v{{.Version}}"
  header: |
    ## StackEye CLI {{.Version}}

    Install:
    ```bash
    # macOS (Homebrew)
    brew install stackeye-io/tap/stackeye

    # Windows (Scoop)
    scoop bucket add stackeye-io https://github.com/StackEye-IO/scoop-bucket
    scoop install stackeye

    # Windows (PowerShell installer)
    iwr -useb https://releases.stackeye.io/install.ps1 | iex

    # Debian/Ubuntu (APT repository)
    curl -fsSL https://releases.stackeye.io/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/stackeye-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/stackeye-archive-keyring.gpg] https://releases.stackeye.io stable main" | sudo tee /etc/apt/sources.list.d/stackeye.list > /dev/null
    sudo apt-get update && sudo apt-get install stackeye

    # RHEL/Fedora/CentOS (DNF)
    sudo rpm --import https://releases.stackeye.io/gpg-key.asc
    sudo tee /etc/yum.repos.d/stackeye.repo << 'REPO'
    [stackeye]
    name=StackEye CLI
    baseurl=https://releases.stackeye.io/yum/stable/$basearch
    enabled=1
    gpgcheck=1
    gpgkey=https://releases.stackeye.io/gpg-key.asc
    REPO
    sudo dnf install stackeye

    # Docker
    docker run --rm ghcr.io/stackeye-io/stackeye-cli:{{.Tag}} version

    # Linux/macOS (curl)
    curl -fsSL https://releases.stackeye.io/install.sh | bash

    # Go install (requires public repo)
    go install github.com/StackEye-IO/stackeye-cli/cmd/stackeye@{{.Tag}}
    ```

# Homebrew tap configuration
# Note: brews section deprecated in v2.10, but still works for CLI tools
# Homebrew Casks are for macOS .app bundles, not CLIs
brews:
  - name: stackeye
    repository:
      owner: StackEye-IO
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    # Use CDN URL for faster downloads (CloudFlare fronts Wasabi S3)
    url_template: "https://releases.stackeye.io/cli/v{{ .Version }}/{{ .ArtifactName }}"
    homepage: https://stackeye.io
    description: "CLI for StackEye uptime monitoring platform"
    license: MIT
    install: |
      bin.install "stackeye"
    test: |
      system "#{bin}/stackeye", "version"
    dependencies:
      - name: git
        type: optional

# Scoop manifest configuration for Windows
scoops:
  - repository:
      owner: StackEye-IO
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    # Use CDN URL for faster downloads (CloudFlare fronts Wasabi S3)
    url_template: "https://releases.stackeye.io/cli/v{{ .Version }}/{{ .ArtifactName }}"
    homepage: https://stackeye.io
    description: "CLI for StackEye uptime monitoring platform"
    license: MIT

# Slack announcement configuration - disabled until release process is established
#
# announce:
#   slack:
#     enabled: false
#     channel: "#releases"
