# GitHub Actions: StackEye Monitoring Integration
# ================================================
#
# This workflow sets up monitoring for your application after deployment.
# Add this to .github/workflows/deploy.yml in your repository.
#
# Required Secrets:
#   STACKEYE_API_KEY - Your StackEye API key (se_...)
#
# Optional Secrets:
#   SLACK_WEBHOOK_URL - For Slack notifications

name: Deploy and Monitor

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: my-application
  APP_URL: https://api.example.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Your deployment steps here
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Your deployment commands

      - name: Wait for deployment to stabilize
        run: sleep 30

  setup-monitoring:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install StackEye CLI
        run: |
          curl -fsSL https://get.stackeye.io/cli | bash
          stackeye version

      - name: Configure StackEye
        env:
          STACKEYE_API_KEY: ${{ secrets.STACKEYE_API_KEY }}
        run: |
          stackeye setup --no-input

      - name: Verify Authentication
        run: stackeye whoami

      # Option 1: Create probe if not exists (idempotent approach)
      - name: Setup Health Check Probe
        env:
          STACKEYE_API_KEY: ${{ secrets.STACKEYE_API_KEY }}
        run: |
          # Check if probe already exists
          if stackeye probe list -o json | jq -e '.[] | select(.name == "${{ env.APP_NAME }} - Health")' > /dev/null 2>&1; then
            echo "Probe already exists, skipping creation"
          else
            stackeye probe create \
              --name "${{ env.APP_NAME }} - Health" \
              --url "${{ env.APP_URL }}/health" \
              --interval 60 \
              --timeout 10 \
              --json-path-check "$.status" \
              --json-path-expected "ok"
          fi

      # Option 2: Use deployment-specific probe (for canary/blue-green)
      - name: Create Deployment Probe
        env:
          STACKEYE_API_KEY: ${{ secrets.STACKEYE_API_KEY }}
        run: |
          stackeye probe create \
            --name "${{ env.APP_NAME }} - ${{ github.sha }}" \
            --url "${{ env.APP_URL }}/health" \
            --interval 30 \
            --timeout 10

      - name: Run Initial Health Check
        env:
          STACKEYE_API_KEY: ${{ secrets.STACKEYE_API_KEY }}
        run: |
          PROBE_ID=$(stackeye probe list -o json | jq -r '.[] | select(.name | contains("${{ env.APP_NAME }}")) | .id' | head -1)
          if [ -n "$PROBE_ID" ]; then
            stackeye probe test "$PROBE_ID"
          fi

  # Optional: Setup notification channels
  setup-notifications:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ vars.SETUP_NOTIFICATIONS == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install StackEye CLI
        run: curl -fsSL https://get.stackeye.io/cli | bash

      - name: Create Slack Channel
        env:
          STACKEYE_API_KEY: ${{ secrets.STACKEYE_API_KEY }}
        run: |
          cat > /tmp/slack-channel.yaml << EOF
          name: "${{ env.APP_NAME }} - Slack Alerts"
          type: slack
          enabled: true
          config:
            webhook_url: "${{ secrets.SLACK_WEBHOOK_URL }}"
          EOF

          # Create channel (ignore error if exists)
          stackeye channel create --from-file /tmp/slack-channel.yaml || true

      - name: Link Channel to Probe
        env:
          STACKEYE_API_KEY: ${{ secrets.STACKEYE_API_KEY }}
        run: |
          PROBE_ID=$(stackeye probe list -o json | jq -r '.[] | select(.name | contains("${{ env.APP_NAME }}")) | .id' | head -1)
          CHANNEL_ID=$(stackeye channel list -o json | jq -r '.[] | select(.name | contains("${{ env.APP_NAME }}")) | .id' | head -1)

          if [ -n "$PROBE_ID" ] && [ -n "$CHANNEL_ID" ]; then
            stackeye probe link-channel "$PROBE_ID" "$CHANNEL_ID" || true
          fi
